### ISSUE TITLE
AUTH: ERROR: column "use_static_key" of relation "session_info" does not exist

### ISSUE THREAD

**Issue by johanbook** [johanbook/meet#69]
Sometimes when spinning up the server one, the following error happens in the auth backend

```
Caused by: org.postgresql.util.PSQLException: ERROR: column "use_static_key" of relation "session_info" does not exist
  Position: 134
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2510)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2245)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:311)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:125)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at io.supertokens.storage.postgresql.QueryExecutorTemplate.update(QueryExecutorTemplate.java:58)
	at io.supertokens.storage.postgresql.QueryExecutorTemplate.update(QueryExecutorTemplate.java:50)
	at io.supertokens.storage.postgresql.queries.SessionQueries.createNewSession(SessionQueries.java:82)
	at io.supertokens.storage.postgresql.Start.createNewSession(Start.java:404)
	... 23 more
```

**Comment by johanbook** [comment]
I fixed this in PROD by dropping the `session_info` table and restarting the service (which triggered it to run a new migration). I will keep this issue open in case the problem resurfaces.
